# Generated by Django 3.2.18 on 2023-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('profiles', '0002_remove_profile_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blog.BlogPost'),
        ),
    ]
