# Generated by Django 3.2.18 on 2023-04-05 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 12, 47, 36, 191, tzinfo=utc)),
        ),
    ]
