# Generated by Django 3.2.18 on 2023-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comments_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog_post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
