# Generated by Django 3.2.18 on 2023-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Football', 'Football'), ('GAA', 'GAA'), ('Rugby', 'Rugby'), ('Other', 'Other')], default='Football', max_length=10),
        ),
    ]
